# Generated by Django 5.2.8 on 2025-12-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share_data',
            name='SOLDIER',
        ),
        migrations.RemoveField(
            model_name='soldier_table',
            name='DEPARTMENT',
        ),
        migrations.RemoveField(
            model_name='soldier_table',
            name='DESIGNATION',
        ),
        migrations.RemoveField(
            model_name='soldier_table',
            name='LOGIN',
        ),
        migrations.DeleteModel(
            name='key_request',
        ),
        migrations.DeleteModel(
            name='share_data',
        ),
        migrations.DeleteModel(
            name='Soldier_table',
        ),
    ]
