# Generated by Django 5.2.8 on 2025-12-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_share_data_key_request_soldier_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier_table',
            name='private_key',
            field=models.TextField(default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldier_table',
            name='public_key',
            field=models.TextField(default=22),
            preserve_default=False,
        ),
    ]
