# Generated by Django 5.2.8 on 2025-12-20 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_soldier_table_private_key_soldier_table_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier_table',
            name='DEPARTMENT',
        ),
        migrations.AddField(
            model_name='soldier_table',
            name='STAFF',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='myapp.staff'),
            preserve_default=False,
        ),
    ]
