# Generated by Django 5.2.5 on 2026-01-10 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_soldier_table_department_soldier_table_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000)),
                ('steg_data_path', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('From_soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From_user', to='myapp.soldier_table')),
                ('To_soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To_user', to='myapp.soldier_table')),
            ],
        ),
    ]
